spring:
  graphql:
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:socialapp
    username: admin
    password: password
  jpa:
    generate-ddl: true

server:
  port: 4100